version: "3"

volumes:
  remote_cache_data:
    driver: local
  redis_data:
    driver: local

services:
  redis:
    image: redis:6.2.6
    volumes:
      - redis_data:/data
  remote-cache:
    image: btwiuse/remote-cache:${STABLE_DOCKER_TAG:-dev}
    ports:
      - "8081:8081"
    volumes:
      - remote_cache_data:/data/cache
      - ./config.toml:/config.toml
